# Build python wheels for indexed_gzip:
#     https://github.com/pauldmccarthy/indexed_gzip
#
# This configuration is based on multibuild:
#     https://github.com/matthew-brett/multibuild
#
# The following environment variables must be defined
#
#   - TWINE_USERNAME: - Username to use when uploading to pypi
#   - TWINE_PASSWORD: - Password to use when uploading to pypi

env:
    global:
        - REPO_DIR=indexed_gzip
        # Change this whenever you need to do a new build
        - BUILD_COMMIT=v1.2.0
        # Set to 0 for a test build, 1 to deploy builds
        - DEPLOY=1
        - BUILD_DEPENDS="Cython numpy"
        - TEST_DEPENDS="numpy pytest coverage pytest-cov six"
        - PLAT=x86_64
        - UNICODE_WIDTH=32

language: python
os: linux
dist: trusty
services: docker

jobs:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - BUILD_SOURCE=1


before_install:
    # Prepare for building
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - source config.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - if [ "x$BUILD_SOURCE" == "x" ]; then build_wheel  $REPO_DIR $PLAT; fi
    - if [ "$BUILD_SOURCE"  == "1" ]; then build_source $REPO_DIR;       fi

script:
    - if [ "x$BUILD_SOURCE" == "x" ]; then install_run $PLAT; fi

after_success:
    - if [[ "$DEPLOY" == "1" ]]; then sh ./deploy.sh "$TRAVIS_BUILD_DIR"/wheelhouse/*; fi
