# Build Windows wheels for indexed_gzip:
#     https://github.com/pauldmccarthy/indexed_gzip
#
# This configuration is based on multibuild:
#     https://github.com/matthew-brett/multibuild
#
# The following environment variables must be defined
#
#   - TWINE_USERNAME: - Username to use when uploading to pypi
#   - TWINE_PASSWORD: - Password to use when uploading to pypi


environment:
    global:
      REPO_DIR: indexed_gzip
      PACKAGE_NAME: indexed_gzip
      # Change this whenever you need to do a new build
      BUILD_COMMIT: v1.3.2
      # Set to 0 for a test build, 1 to deploy builds
      DEPLOY: 1
      BUILD_DEPENDS: "Cython numpy zlib"
      TEST_DEPENDS: "numpy nibabel pytest six"

      # Mak cygwin/bash run in the current directory
      CHERE_INVOKING: 1

      CONDABAT: conda.bat

    matrix:

      - image: Visual Studio 2015
        PYTHON: "C:\\Miniconda"
        PYTHON_VERSION: "2.7"
        PYTHON_ARCH: "32"
      - image: Visual Studio 2015
        PYTHON: "C:\\Miniconda-x64"
        PYTHON_VERSION: "2.7"
        PYTHON_ARCH: "64"
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda35"
        PYTHON_VERSION: "3.5"
        PYTHON_ARCH: "32"
        CONDABAT: ""
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda35-x64"
        PYTHON_VERSION: "3.5"
        PYTHON_ARCH: "64"
        CONDABAT: ""
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda36"
        PYTHON_VERSION: "3.6"
        PYTHON_ARCH: "32"
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda36-x64"
        PYTHON_VERSION: "3.6"
        PYTHON_ARCH: "64"
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda37"
        PYTHON_VERSION: "3.7"
        PYTHON_ARCH: "32"
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda37-x64"
        PYTHON_VERSION: "3.7"
        PYTHON_ARCH: "64"
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda37"
        PYTHON_VERSION: "3.8"
        PYTHON_ARCH: "32"
      - image: Visual Studio 2019
        PYTHON: "C:\\Miniconda38-x64"
        PYTHON_VERSION: "3.8"
        PYTHON_ARCH: "64"


install:

  # Get needed submodules
  - git submodule update --init --recursive

  # Put miniconda on the path
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"


build_script:

  # install build dependencies
  - conda config --set auto_update_conda false
  - conda clean --all --yes
  - conda install --yes tqdm
  - conda install --yes conda-build
  - conda create --yes -n build_env python=%PYTHON_VERSION%  %BUILD_DEPENDS%
  - CALL %CONDABAT% activate build_env
  - conda update  --yes setuptools pip
  - conda install --yes readme_renderer cmarkgfm twine
  - set ZLIB_HOME=%PYTHON%\\Library

  # Build and install the wheel
  - cd %REPO_DIR%
  - git checkout %BUILD_COMMIT%

  # work around some conda issue that I don't understand
  # https://github.com/conda/conda/issues/6057
  - python setup.py bdist_wheel
  - twine check dist/*


test_script:
  - conda create --yes -n test_env python=%PYTHON_VERSION% %TEST_DEPENDS%
  - CALL conda.bat activate test_env
  - conda update  --yes setuptools pip

  # workaround cpython bug: https://github.com/matplotlib/matplotlib/issues/9176
  - python -c "import sys; sys.exit(not (3,) < sys.version_info < (3,6,3))" && (curl -sL https://github.com/python/cpython/pull/1224.patch | patch -fsup 1 -d %CONDA_PREFIX% ) || ( set errorlevel=0 )

  - pip install --no-index --find-links dist %PACKAGE_NAME%
  - pip install %TEST_DEPENDS%
  - cd ..
  - md testing
  - cd testing
  - cp ..\\%REPO_DIR%\\conftest.py .
  - pytest -v -s -m indexed_gzip_test          --niters 250 --nelems=rnd_1048576 --pyargs indexed_gzip
  - pytest -v -s -m indexed_gzip_test --concat --niters 250 --nelems=rnd_1048576 --pyargs indexed_gzip
  - cd ..\\%REPO_DIR%\\


on_success:
  - C:\\cygwin\\bin\\bash -e -l -c 'if [ "$DEPLOY" == "1" ]; then pwd; ls; sh ../deploy.sh ./dist/*; fi'
